import { ShopProduct } from '@/types';

export const shopProducts: ShopProduct[] = [
  // Books
  {
    id: 'rigveda-book',
    name: 'Rigveda - Complete Translation',
    category: 'books',
    description: 'Complete English translation of the Rigveda with Sanskrit text and commentary',
    price: 1250,
    image: '/images/shop/rigveda-book.jpg',
    inStock: true,
    shopLink: 'https://www.amazon.in/s?k=rigveda+complete+translation',
  },
  {
    id: 'bhagavad-gita',
    name: 'Bhagavad Gita - As It Is',
    category: 'books',
    description: 'Authoritative translation and commentary on the Bhagavad Gita',
    price: 450,
    image: '/images/shop/bhagavad-gita.jpg',
    inStock: true,
    shopLink: 'https://www.amazon.in/s?k=bhagavad+gita+as+it+is',
  },
  {
    id: 'upanishads-collection',
    name: 'Complete Upanishads Collection',
    category: 'books',
    description: 'All 108 Upanishads with translations and commentaries',
    price: 1899,
    image: '/images/shop/upanishads-collection.jpg',
    inStock: true,
    shopLink: 'https://www.amazon.in/s?k=upanishads+complete+collection',
  },
  {
    id: 'puranas-set',
    name: '18 Puranas - Complete Set',
    category: 'books',
    description: 'Complete collection of all 18 Puranas with translations',
    price: 5999,
    image: '/images/shop/puranas-set.jpg',
    inStock: true,
    shopLink: 'https://www.amazon.in/s?k=18+puranas+complete+set',
  },
  {
    id: 'tantra-texts',
    name: 'Tantra Scriptures Collection',
    category: 'books',
    description: 'Collection of major Tantra texts with translations',
    price: 2499,
    image: '/images/shop/tantra-texts.jpg',
    inStock: true,
    shopLink: 'https://www.amazon.in/s?k=tantra+scriptures+collection',
  },
  {
    id: 'ramayana',
    name: 'Ramayana - Valmiki',
    category: 'books',
    description: 'Complete Ramayana by Sage Valmiki with translation',
    price: 899,
    image: '/images/shop/ramayana.jpg',
    inStock: true,
    shopLink: 'https://www.amazon.in/s?k=ramayana+valmiki+complete',
  },
  {
    id: 'mahabharata',
    name: 'Mahabharata - Complete',
    category: 'books',
    description: 'Complete Mahabharata epic with translation',
    price: 3499,
    image: '/images/shop/mahabharata.jpg',
    inStock: true,
    shopLink: 'https://www.amazon.in/s?k=mahabharata+complete+translation',
  },
  // Idols
  {
    id: 'shiva-idol',
    name: 'Lord Shiva Idol - Brass',
    category: 'idols',
    description: 'Beautiful brass idol of Lord Shiva in meditative pose',
    price: 2500,
    image: '/images/shop/shiva-idol.jpg',
    inStock: true,
  },
  {
    id: 'vishnu-idol',
    name: 'Lord Vishnu Idol - Brass',
    category: 'idols',
    description: 'Elegant brass idol of Lord Vishnu with conch and discus',
    price: 2800,
    image: '/images/shop/vishnu-idol.jpg',
    inStock: true,
  },
  {
    id: 'ganesha-idol',
    name: 'Lord Ganesha Idol - Brass',
    category: 'idols',
    description: 'Charming brass idol of Lord Ganesha, remover of obstacles',
    price: 1800,
    image: '/images/shop/ganesha-idol.jpg',
    inStock: true,
  },
  {
    id: 'lakshmi-idol',
    name: 'Goddess Lakshmi Idol - Brass',
    category: 'idols',
    description: 'Beautiful brass idol of Goddess Lakshmi, goddess of wealth',
    price: 2200,
    image: '/images/shop/lakshmi-idol.jpg',
    inStock: true,
  },
  {
    id: 'saraswati-idol',
    name: 'Goddess Saraswati Idol - Brass',
    category: 'idols',
    description: 'Elegant brass idol of Goddess Saraswati, goddess of knowledge',
    price: 2100,
    image: '/images/shop/saraswati-idol.jpg',
    inStock: true,
  },
  {
    id: 'durga-idol',
    name: 'Goddess Durga Idol - Brass',
    category: 'idols',
    description: 'Powerful brass idol of Goddess Durga with weapons',
    price: 3200,
    image: '/images/shop/durga-idol.jpg',
    inStock: true,
  },
  {
    id: 'krishna-idol',
    name: 'Lord Krishna Idol - Brass',
    category: 'idols',
    description: 'Beautiful brass idol of Lord Krishna with flute',
    price: 2400,
    image: '/images/shop/krishna-idol.jpg',
    inStock: true,
  },
  {
    id: 'hanuman-idol',
    name: 'Lord Hanuman Idol - Brass',
    category: 'idols',
    description: 'Devotional brass idol of Lord Hanuman',
    price: 1900,
    image: '/images/shop/hanuman-idol.jpg',
    inStock: true,
  },
  // Japa Mala
  {
    id: 'tulsi-mala',
    name: 'Tulsi Japa Mala - 108 Beads',
    category: 'japa-mala',
    description: 'Sacred Tulsi wood japa mala with 108 beads and guru bead',
    price: 450,
    image: '/images/shop/tulsi-mala.jpg',
    inStock: true,
  },
  {
    id: 'rudraksha-mala',
    name: 'Rudraksha Japa Mala - 108 Beads',
    category: 'japa-mala',
    description: 'Authentic Rudraksha japa mala with 108 beads',
    price: 1200,
    image: '/images/shop/rudraksha-mala.jpg',
    inStock: true,
  },
  {
    id: 'sandalwood-mala',
    name: 'Sandalwood Japa Mala - 108 Beads',
    category: 'japa-mala',
    description: 'Fragrant sandalwood japa mala with 108 beads',
    price: 800,
    image: '/images/shop/sandalwood-mala.jpg',
    inStock: true,
  },
  {
    id: 'crystal-mala',
    name: 'Crystal Japa Mala - 108 Beads',
    category: 'japa-mala',
    description: 'Beautiful crystal japa mala with 108 beads',
    price: 1500,
    image: '/images/shop/crystal-mala.jpg',
    inStock: true,
  },
  {
    id: 'lotus-seed-mala',
    name: 'Lotus Seed Japa Mala - 108 Beads',
    category: 'japa-mala',
    description: 'Sacred lotus seed japa mala with 108 beads',
    price: 950,
    image: '/images/shop/lotus-seed-mala.jpg',
    inStock: true,
  },
  // Devotional Items
  {
    id: 'brass-lamp',
    name: 'Brass Puja Lamp',
    category: 'devotional-items',
    description: 'Traditional brass oil lamp for puja ceremonies',
    price: 650,
    image: '/images/shop/brass-lamp.jpg',
    inStock: true,
  },
  {
    id: 'incense-sticks',
    name: 'Premium Incense Sticks - Pack of 12',
    category: 'devotional-items',
    description: 'High-quality natural incense sticks in various fragrances',
    price: 350,
    image: '/images/shop/incense-sticks.jpg',
    inStock: true,
  },
  {
    id: 'puja-thali',
    name: 'Brass Puja Thali Set',
    category: 'devotional-items',
    description: 'Complete brass puja thali with accessories',
    price: 1200,
    image: '/images/shop/puja-thali.jpg',
    inStock: true,
  },
  {
    id: 'yantra-copper',
    name: 'Sri Yantra - Copper',
    category: 'devotional-items',
    description: 'Sacred Sri Yantra engraved on copper plate',
    price: 1800,
    image: '/images/shop/yantra-copper.jpg',
    inStock: true,
  },
  {
    id: 'bell-brass',
    name: 'Brass Puja Bell',
    category: 'devotional-items',
    description: 'Traditional brass bell for puja ceremonies',
    price: 450,
    image: '/images/shop/bell-brass.jpg',
    inStock: true,
  },
  {
    id: 'camphor-box',
    name: 'Brass Camphor Box',
    category: 'devotional-items',
    description: 'Elegant brass box for camphor during aarti',
    price: 550,
    image: '/images/shop/camphor-box.jpg',
    inStock: true,
  },
  {
    id: 'coconut-shell',
    name: 'Coconut Shell Puja Set',
    category: 'devotional-items',
    description: 'Traditional coconut shell items for puja',
    price: 300,
    image: '/images/shop/coconut-shell.jpg',
    inStock: true,
  },
  {
    id: 'kumkum-box',
    name: 'Brass Kumkum Box',
    category: 'devotional-items',
    description: 'Beautiful brass box for kumkum and sindoor',
    price: 400,
    image: '/images/shop/kumkum-box.jpg',
    inStock: true,
  }
];
